Add populate eventStore when starting eventStore

diff --git a/deploy/docker/run/runAllServers b/deploy/docker/run/runAllServers
--- a/deploy/docker/run/runAllServers
+++ b/deploy/docker/run/runAllServers
@@ -1,3 +1,9 @@
 #! /bin/bash
 
-server/eventstore/run > eventStore_container_Id
+for server in "eventstore"  
+do
+    pushd server/$server
+    ./run
+    ./test || echo "error on $server" && exit 1
+    popd
+done
