Add container for all services

diff --git a/deploy/docker/run/runAllServers b/deploy/docker/run/runAllServers
--- a/deploy/docker/run/runAllServers
+++ b/deploy/docker/run/runAllServers
@@ -1,9 +1,14 @@
 #! /bin/bash
 
-for server in "eventstore"  
+scream() {
+    echo "error on $1"
+    exit 1
+}
+
+for server in "eventstore" "broker" "pricing" "reference"
 do
-    pushd server/$server
-    ./run
-    ./test || echo "error on $server" && exit 1
-    popd
+    cd server/$server
+    ./run  || scream $server
+    ./test || scream $server
+    cd ../..
 done
