update save/load mecanism to follow volume changes

diff --git a/deploy/e2e/loadContainers b/deploy/e2e/loadContainers
--- a/deploy/e2e/loadContainers
+++ b/deploy/e2e/loadContainers
@@ -1,10 +1,39 @@
 #! /bin/bash
 
-echo "Loading containers"
+# fail fast
+set -euo pipefail
 
-for container in "mono" "crossbar" "eventstore" "nginx" "dnupackage" "nodemodules"
-do
-  if [[ -e ~/docker/$container.tar ]]; then 
-    docker load -i ~/docker/$container.tar && echo "$container loaded" 
-  fi
-done
+# echo "Loading containers"
+
+# for container in "mono" "crossbar" "eventstore" "nginx" "dnupackage" "nodemodules"
+# do
+#   if [[ -e ~/docker/$container.tar ]]; then 
+#     docker load -i ~/docker/$container.tar && echo "$container loaded" 
+#   fi
+# done
+
+. ../config
+
+echo "start a backup container ..."
+alwaysCommand="while true; do echo ping; sleep 60; done"
+restoreContainer="loadpackagecontainer"
+
+docker rm ${restoreContainer} || true 
+docker run -d                                   \
+  --name ${restoreContainer}                    \
+  -v ${dnupackageContainer}:/package            \
+  -v ${nodemodulesContainer}:/nodemodules       \
+  ${ubuntuContainer} bash -c "${alwaysCommand}"
+
+echo "copy packages to the container ..."
+docker cp ~/packages/${dnupackageContainer}.tar \
+          ${restoreContainer}:/tmp/${dnupackageContainer}.tar 
+docker cp ~/packages/${nodemodulesContainer}.tar \
+          ${restoreContainer}:/tmp/${nodemodulesContainer}.tar
+
+echo "untar into the container"
+docker exec -t ${restoreContainer} \
+  bash -c "cd /tmp && tar xvf /tmp/${dnupackageContainer}.tar && cp -r data/* /package"
+docker exec -t ${restoreContainer} \
+  bash -c "cd /tmp && tar xvf /tmp/${nodemodulesContainer}.tar  && cp -r data/* /nodemodules"
+
diff --git a/deploy/e2e/saveContainers b/deploy/e2e/saveContainers
--- a/deploy/e2e/saveContainers
+++ b/deploy/e2e/saveContainers
@@ -1,13 +1,39 @@
 #! /bin/bash
 
+# fail fast
+set -euo pipefail
+
 . ../config
 
 mkdir -p ~/docker
+mkdir -p ~/packages
 
 echo "Saving containers"
-docker save $monoContainer        > ~/docker/mono.tar
-docker save $crossbarContainer    > ~/docker/crossbar.tar
-docker save $eventstoreContainer  > ~/docker/eventstore.tar
-docker save $nginxContainer       > ~/docker/nginx.tar
-docker save $dnupackageContainer  > ~/docker/dnupackage.tar
-docker save $nodemodulesContainer > ~/docker/nodemodules.tar
+# docker save $monoContainer        > ~/docker/mono.tar
+# docker save $crossbarContainer    > ~/docker/crossbar.tar
+# docker save $eventstoreContainer  > ~/docker/eventstore.tar
+# docker save $nginxContainer       > ~/docker/nginx.tar
+
+saveCommand="tar cvf /tmp/backup.tar /data"
+
+echo "dnu packages"
+docker rm ${dnupackageContainer} || true
+docker run -t                     \
+  --name ${dnupackageContainer}   \
+  -v ${dnupackageContainer}:/data \
+  ${ubuntuContainer}              \
+  bash -c "$saveCommand"
+
+docker cp ${dnupackageContainer}:/tmp/backup.tar \
+          ~/packages/${dnupackageContainer}.tar
+
+echo "node_modules"
+docker rm ${nodemodulesContainer} || true
+docker run -t                      \
+  --name ${nodemodulesContainer}   \
+  -v ${nodemodulesContainer}:/data \
+  ${ubuntuContainer}               \
+  bash -c "$saveCommand"
+
+docker cp ${nodemodulesContainer}:/tmp/backup.tar \
+          ~/packages/${nodemodulesContainer}.tar
