Add release mode for running containers

diff --git a/deploy/docker/run/analytics/run b/deploy/docker/run/analytics/run
--- a/deploy/docker/run/analytics/run
+++ b/deploy/docker/run/analytics/run
@@ -1,17 +1,26 @@
 #! /bin/bash
 
-build=""
-if [[ $1 != "" ]];then
+releaseMode=""
+if [[ $1 == "release" ]];then
+  releaseMode="--configuration Release"
+  build=""
+elif [[ $1 != "" ]];then
   build=".$1"
 fi
+if [[ $2 == "release" ]];then
+  releaseMode="--configuration Release"
+fi
+
+#fail fast
+set euo -pipefail
 
 echo "Analytics"
 . ../../../config
 
-startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run a"
+startCommand="dnx $releaseMode -p Adaptive.ReactiveTrader.Server.Launcher run a"
 waitCommand="while true; do echo ping; sleep 60; done"
 
-docker rm analytics 2&> garbage
+docker rm analytics 2&> garbage || true
 
 docker run -d --net=host                     \
      --name analytics                        \
diff --git a/deploy/docker/run/eventstore/run b/deploy/docker/run/eventstore/run
--- a/deploy/docker/run/eventstore/run
+++ b/deploy/docker/run/eventstore/run
@@ -1,15 +1,18 @@
 #! /bin/bash
 
 build=""
-if [[ $1 != "" ]];then
+if [[ $1 != "" && $1 != "release" ]];then
   build=".$1"
 fi
+
+# fail fast
+set -euo pipefail
 
 echo "EventStore"
 
 . ../../../config
 
-docker rm eventstore 2&> garbage
+docker rm eventstore 2&> garbage || true
 
 docker run -d --net=host              \
   --name eventstore                   \
diff --git a/deploy/docker/run/referencedataread/run b/deploy/docker/run/referencedataread/run
--- a/deploy/docker/run/referencedataread/run
+++ b/deploy/docker/run/referencedataread/run
@@ -1,18 +1,29 @@
 #! /bin/bash
 
-build=""
 if [[ $1 != "" ]];then
   build=".$1"
 fi
+releaseMode=""
+
+if [[ $1 == "release" ]];then
+  releaseMode="--configuration Release"
+  build=""
+fi
+if [[ $2 == "release" ]];then
+  releaseMode="--configuration Release"
+fi
+
+#fail fast
+set euo -pipefail
 
 echo "ReferenceDataRead"
 
 . ../../../config
 
-startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run ref"
+startCommand="dnx $releaseMode -p Adaptive.ReactiveTrader.Server.Launcher run ref"
 waitCommand="while true; do echo ping; sleep 60; done"
 
-docker rm reference 2&> garbage
+docker rm reference 2&> garbage || true
 
 docker run -d --net=host                      \
      --name reference                         \
diff --git a/deploy/docker/run/tradeexecution/run b/deploy/docker/run/tradeexecution/run
--- a/deploy/docker/run/tradeexecution/run
+++ b/deploy/docker/run/tradeexecution/run
@@ -1,18 +1,27 @@
 #! /bin/bash
 
-build=""
-if [[ $1 != "" ]];then
+releaseMode=""
+if [[ $1 == "release" ]];then
+  releaseMode="--configuration Release"
+  build=""
+elif [[ $1 != "" ]];then
   build=".$1"
 fi
+if [[ $2 == "release" ]];then
+  releaseMode="--configuration Release"
+fi
+
+#fail fast
+set euo -pipefail
 
 echo "TradeExecution"
 
 . ../../../config
 
-startCommand="dnx -p Adaptive.ReactiveTrader.Server.Launcher run exec"
+startCommand="dnx $releaseMode -p Adaptive.ReactiveTrader.Server.Launcher run exec"
 waitCommand="while true; do echo ping; sleep 60; done"
 
-docker rm tradeexecution 2&> garbage
+docker rm tradeexecution 2&> garbage || true
 
 docker run -d --net=host                     \
      --name tradeexecution                   \
diff --git a/deploy/docker/run/web/run b/deploy/docker/run/web/run
--- a/deploy/docker/run/web/run
+++ b/deploy/docker/run/web/run
@@ -1,15 +1,18 @@
 #! /bin/bash
 
 build=""
-if [[ $1 != "" ]];then
+if [[ $1 != "" && $1 != "release" ]];then
   build=".$1"
 fi
+
+#fail fast
+set euo -pipefail
 
 echo "Web"
 
 . ../../../config
 
-docker rm web 2&> garbage
+docker rm web 2&> garbage || true
 
 command="cp /localhost/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
 docker run -d --net=host \
