Add kubernetes deployment

diff --git a/deploy/kubernetes/templates/generate_rc_manifest b/deploy/kubernetes/templates/generate_rc_manifest
--- a/deploy/kubernetes/templates/generate_rc_manifest
+++ b/deploy/kubernetes/templates/generate_rc_manifest
@@ -1,5 +1,9 @@
 #! /bin/bash
 
+if [[ $# != 3 ]];then 
+  echo "parameter error: service namespace build"  
+  exit 1 
+fi
 service=$1
 namespace=$2
 build=$3
@@ -16,7 +20,7 @@ fi
 
 
 manifestFolder="../manifests"
-rcFile="$manifestFolder/rc.yml"
+rcFile="$manifestFolder/$service-rc.yml"
 
 mkdir -p $manifestFolder
 
@@ -37,5 +41,4 @@ sed -i  "s/__MAJOR__/$vMajor/g" $rcFile
 sed -i  "s/__MINOR__/$vMinor/g" $rcFile
 sed -i  "s/__BUILD__/$build/g" $rcFile
 sed -i  "s|__DOCKERIMAGE__|$dockerImage|g" $rcFile
-#sed -i  "s/__CONTAINERPORT__/80/g" $rcFile
 sed -i  "s/__NAMESPACE__/$namespace/g" $rcFile
diff --git a/deploy/kubernetes/templates/generate_svc_manifest b/deploy/kubernetes/templates/generate_svc_manifest
--- a/deploy/kubernetes/templates/generate_svc_manifest
+++ b/deploy/kubernetes/templates/generate_svc_manifest
@@ -1,7 +1,13 @@
 #! /bin/bash
 
+if [[ $# != 2 ]];then 
+  echo "parameter error: service namespace"  
+  exit 1 
+fi
 service=$1
 namespace=$2
+
+
 . ../../config
 
 if [[ $vMajor = "" ]];then
@@ -14,7 +20,7 @@ if [[ $vMinor = "" ]];then
 fi
 
 manifestFolder="../manifests"
-svcFile="$manifestFolder/svc.yml"
+svcFile="$manifestFolder/$service-svc.yml"
 
 mkdir -p $manifestFolder
 
@@ -23,6 +29,4 @@ cp ./$service/svc.yml $svcFile
 sed -i  "s/__SERVICE__/$service/g" $svcFile
 sed -i  "s/__MAJOR__/$vMajor/g" $svcFile
 sed -i  "s/__MINOR__/$vMinor/g" $svcFile
-#sed -i  "s/__CONTAINERPORT__/80/g" $svcFile
-#sed -i  "s/__SERVICEPORT__/80/g" $svcFile
 sed -i  "s/__NAMESPACE__/$namespace/g" $svcFile
